### ISSUE TITLE
about concept

### ISSUE THREAD

**Issue by chenjianqiang199526** [ZiyueWu59/CCA#1]
how to get concept?can you give the script?

**Comment by ZiyueWu59** [comment]
We count the frequencies of each word from the annotations of training set, and select some high-frequency words as concept. After that we structure their co-occurance matrix. For example, if the word "person" and the word "car" both appear in the sentence "A person is driving a car", their co-occurance frequency plus one. You can also reference the paper "_Consensusaware visual-semantic embedding for image-text matching_".

**Comment by chenjianqiang199526** [comment]
> 

Thank you for your generous reply
